name: Run sfdx scanner
on:
  pull_request:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run: npm install sfdx-cli
      - name: Run sfdx scanner
        run: |
          sfdx scanner:run -t src
          sfdx scanner:run -c security,best-practices
          sfdx scanner:run -r rulesets/apex_security_best_practices.xml
