name: SFDX Apex PMD Code scanner
on:
  pull_request:
    branches:
      - main
      - testing
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run:  |
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Run sfdx scanner
        run: |
          sfdx scanner:run -t src --format table -r rulesets/apex/quickstart.xml
          

