name: SFDX Apex PMD Code scanner
on:
  pull_request:
    branches:
      - main
      - testing
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run:  |
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Run sfdx scanner
        run: |
          sfdx scanner:run -t src
          sfdx scanner:run --format table
          sfdx scanner:run -c security,best-practices
          sfdx scanner:run -r rulesets/apex_security_best_practices.xml
          sfdx scanner:run -n
          sfdx scanner:run exit 1
