name: SFDX Apex PMD Code scanner
on:
  pull_request:
    branches:
      - main
      - testing
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run:  |
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Run sfdx scanner
        run: |
          sfdx scanner:run -target src
          sfdx scanner:run --format table
          sfdx scanner:run --category Security
          sfdx scanner:run --ruleset Salesforce Security Best Practices
          sfdx scanner:run --normalize-severity
          sfdx scanner:run --violations-cause-error
