name: SFDX Apex PMD Code scanner
on:
  pull_request:
    branches:
      - main
      - testing
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run:  |
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Run sfdx scanner
        run: |
          sfdx scan -t src
          sfdx scan --format table
          sfdx scan -c security,best-practices
          sfdx scan -r rulesets/apex_security_best_practices.xml
          sfdx scan  -n
          sfdx scan exit 1
